* Rails Generators & Functions
```
$ rails generate controller StaticPages home help
$ rails generate model User name:string email:string
$ rails generate integration_test users_signup
```

`$ bundle` === `$ bundle install`

```
$ rails routes
```

* Ruby Notes
.inspect method on objects returns a string representation

%w[foo bar baz] is used to convert that innard into an array of strings

String interpolation: "some text #{varToInterpolate} some text"

* Database Migrations
Necessary to change our database in any way.

`$ rails generate migrations new_mig some_field:string`

then edit the change function in db/migrate/XXXXXXXXX_new_mig.rb to do what is necessary 

* Heroku
```
$ git push heroku master
$ heroku run rails db:migrate
$ heroku run console --sandbox
$ heroku apps:info

$ heroku pg:reset DATABASE
$ heroku pg:psql --app colab0 DATABASE
```

can look at them through heroku CLI
```
$ heroku config:get SENDGRID_USERNAME
$ heroku config:get SENDGRID_PASSWORD
```



* TODO

Controllers
1) CREATE USER -- for now, CREATE SELLER
2) CREATE PROPOSAL -- assoc with seller rather than user. REMEMBER to also assoc with publisher

Views
1) Show sites for each proposal

* PROPOSAL
summary/title 200 characters
description
site
seller NAME from PUBLISHER
total price: TBD 
type: video, gallery, article   ENUM

* SITE
categories ENUM

SHOW LIST FOR site


* TODO
publisher creation process

Team LEAD can invite people
Emailer

publisher --- "validated" field. confirmed by colab

now I have an interesting problem. I can create proposals as a user as long as that proposal has a site attached. Interesting.


* TODO
user signup ---- must already exist in database, with connection to publisher


new invitation table
