# config/choices.yml

integration:
  - 'Custom'
  - 'Sponsored'
types:
  - 'Photo Gallery'
  - 'Product Gallery'
  - 'Video Series/Gallery'
  - 'Influencer Video'
  - 'Editorial Video'
  - 'Editorial Post/Article'
  - 'Whitepaper'
  - 'Research'
  - 'Publisher Blog Post'
  - 'Influencer Blog Posts'
  - 'Influencer Product Placement'
  - 'Editorial Product Placement'
  - 'Quiz'
  - 'Infographic'
  - 'Game'
  - 'Editorial Social Post'
  - 'Influencer Social Post'
  - 'Audio Playlist'
  - 'Video Playlist'
  - 'Content Hub'
  - 'In-App Experience'
  - 'First to Market/Beta Tests'

# Up to 3 per proposal.
categories:
  - 'Lifestyle'
  - 'Music'
  - 'News'
  - 'Finance'
  - 'Entertainment'
  - 'Celebrity'
  - 'Blog'
  - 'Sports'
  - 'Fashion'
  - 'Beauty'
  - 'Social'
  - 'Video'
  - 'Automotive'
  - 'Travel'
  - 'Education'
  - 'Opinion'
  - 'Employment'
  - 'Real Estate'
  - 'Local Community'
  - 'Kids'
  - 'Technology & Computing'
  - 'Home & Garden'
  - 'Parenting & Family'
  - 'Science'
  - 'Video'
  - 'Food & Drink'
  - 'Special Interest'
  - 'Review Sites'

objectives:
  - name: 'Awareness'
    kpis:
    - 'Reach'
    - 'Impressions'
    - 'Video Views'
    - 'Page Views'
  - name: 'Engagement'
    kpis:
    - 'CTR'
    - 'Like Rate'
    - 'Comment Rate'
    - 'Share Rate'
    - 'Total Engagement Rate'
  - name: 'Direct Response'
    kpis:
    - 'Conversion rate'
    - 'Revenue'
    - 'Orders'
    - 'Return on ad spend (ROAS)'
    - 'Email/data capture'
    - 'Click through rate'
    - 'Store visitation rate'
    - 'Click to call'
    - 'Sign-up rate'
