default: &default
  adapter: postgresql
  encoding: unicode
  
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: colab_development

  # Use default user/pass
  username:
  password:

test:
  <<: *default
  database: colab_test

# Heroku-Defined
production:
  <<: *default
  database: colab_production